=== tormaantal/YK11Q1_XMLGyak/XMLTaskYk11q1/1. feladat/XMLSchemaYk11q1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <!-- Szerkezet felépítése -->
    <xs:element name="handball">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="team" type="teamTipus" maxOccurs="unbounded"/>
                <xs:element name="player" type="playerTipus" maxOccurs="unbounded"/>
                <xs:element name="coach" type="coachTipus" maxOccurs="unbounded"/>
                <xs:element name="match" type="matchTipus" maxOccurs="unbounded"/>
                <xs:element name="referee" type="refereeTipus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        
        <!-- PK kulcsok definiálása -->
        <xs:key name="player_kulcs">
            <xs:selector xpath="player"/>
            <xs:field xpath="@idP"/>
        </xs:key>
        <xs:key name="coach_kulcs">
            <xs:selector xpath="coach"/>
            <xs:field xpath="@idC"/>
        </xs:key>
        <xs:key name="team_kulcs">
            <xs:selector xpath="team"/>
            <xs:field xpath="@idT"/>
        </xs:key>
        <xs:key name="referee_kulcs">
            <xs:selector xpath="referee"/>
            <xs:field xpath="@idR"/>
        </xs:key>
        
        <!-- FK kulcsok definiálása -->
        <xs:keyref refer="team_kulcs" name="team_idegen_kulcs">
            <xs:selector xpath="match"/>
            <xs:field xpath="@m_t"/>
        </xs:keyref>
        <xs:keyref refer="referee_kulcs" name="referee_idegen_kulcs">
            <xs:selector xpath="match"/>
            <xs:field xpath="@m_r"/>
        </xs:keyref>
        <xs:keyref refer="team_kulcs" name="team_coach_idegen_kulcs">
            <xs:selector xpath="coach"/>
            <xs:field xpath="@c_t"/>
        </xs:keyref>
        <xs:keyref refer="team_kulcs" name="team_player_idegen_kulcs">
            <xs:selector xpath="player"/>
            <xs:field xpath="@p_t"/>
        </xs:keyref>
        
        <!-- 1:1 kapcsolat létrehozása -->
        <xs:unique name="unique_coach">
            <xs:selector xpath="coach"></xs:selector>
            <xs:field xpath="@c_t"></xs:field>
        </xs:unique>
        
    </xs:element>
    <!-- Egyszerű típusok definiálása -->
    <xs:simpleType name="rankTipus">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="12"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="postTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Kapus"/>
            <xs:enumeration value="Szélső"/>
            <xs:enumeration value="Beálló"/>
            <xs:enumeration value="Irányító"/>
            <xs:enumeration value="Átlövő"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Komplex típusok definiálása -->
    <xs:complexType name="birthdateTipus">
        <xs:sequence>
            <xs:element name="year">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:totalDigits value="4"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="month">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:totalDigits value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="day">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:totalDigits value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="teamTipus">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="point" type="xs:integer"/>
            <xs:element name="rank" type="rankTipus"/>
        </xs:sequence>
        <xs:attribute name="idT" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="playerTipus">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="post" type="postTipus"/>
        </xs:sequence>
        <xs:attribute name="idP" type="xs:string" use="required"/>
        <xs:attribute name="p_t" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="coachTipus">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="birthdate" type="birthdateTipus"/>
        </xs:sequence>
        <xs:attribute name="idC" type="xs:string" use="required"/>
        <xs:attribute name="c_t" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="matchTipus">
        <xs:sequence>
            <xs:element name="location" type="xs:string"/>
            <xs:element name="date" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="m_t" type="xs:string" use="required"/>
        <xs:attribute name="m_r" type="xs:string" use="required"/>
    </xs:complexType>  
    
    <xs:complexType name="refereeTipus">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="age" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="idR" type="xs:string" use="required"/>
    </xs:complexType>
    
</xs:schema>

=== tormaantal/YK11Q1_XMLGyak/XMLTaskYk11q1/1. feladat/XMLYk11q1.xml
<?xml version="1.0" encoding="UTF-8"?>
<handball xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="XMLSchemaYk11q1.xsd">
    <!-- Három különböző team példány egyedi ID-val és adatokkal-->
    <team idT="t1">
        <name>DVTK</name>
        <point>12</point>
        <rank>1</rank>
    </team>
    <team idT="t2">
        <name>PLER</name>
        <point>10</point>
        <rank>2</rank>
    </team>
    <team idT="t3">
        <name>DEAC</name>
        <point>8</point>
        <rank>3</rank>
    </team>
    <!-- Három player példány egyedi ID-val, adatokkal és idegenkulccsal -->
    <player idP="p1" p_t="t1">
        <name>Torma Antal</name>
        <post>Kapus</post>
    </player>
    <player idP="p2" p_t="t3">
        <name>Kiss András</name>
        <post>Beálló</post>
    </player>
    <player idP="p3" p_t="t2">
        <name>Nagy Róbert</name>
        <post>Irányító</post>
    </player>
    <!-- Három coach példány egyedi ID-val, adatokkal és idegenkulccsal  -->
    <coach idC="c1" c_t="t3">
        <name>Gipsz Jakab</name>
        <birthdate>
            <year>1980</year>
            <month>05</month>
            <day>26</day>
        </birthdate>
    </coach>
    <coach idC="c2" c_t="t1">
        <name>Molnár András</name>
        <birthdate>
            <year>1970</year>
            <month>07</month>
            <day>11</day>
        </birthdate>
    </coach>
    <coach idC="c3" c_t="t2">
        <name>Tamás Tamás</name>
        <birthdate>
            <year>1992</year>
            <month>12</month>
            <day>01</day>
        </birthdate>
    </coach>
    <!-- Három match példány melyek kettő idegenkulcsot tartalmazznak -->
    <match m_t="t2" m_r="r1">
        <location>Budapest</location>
        <date>2022-10-31</date>
    </match>
    <match m_t="t1" m_r="r3">
        <location>Miskolc</location>
        <date>2022-11-19</date>
    </match>
    <match m_t="t3" m_r="r2">
        <location>Debrecen</location>
        <date>2023-02-02</date>
    </match>
    <!-- Három referee példány ID-val és adatokkal -->
    <referee idR="r1">
        <name>Katona János</name>
        <age>42</age>
    </referee>
    <referee idR="r2">
        <name>Tóth István</name>
        <age>45</age>
    </referee>
    <referee idR="r3">
        <name>Nagy Péter</name>
        <age>22</age>
    </referee>
</handball>

=== tormaantal/YK11Q1_XMLGyak/XMLTaskYk11q1/XMLYk11q1.xml
<?xml version="1.0" encoding="UTF-8"?>
<handball xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="XMLSchemaYk11q1.xsd">
    <!-- Öt különböző team példány egyedi ID-val és adatokkal-->
    <team idT="t1">
        <name>DVTK</name>
        <foundation>
            <year>1910</year>
            <month>01</month>
            <day>01</day>
        </foundation>
        <rank>NBII</rank>
    </team>
    <team idT="t2">
        <name>PLER</name>
        <foundation>
            <year>1986</year>
            <month>06</month>
            <day>15</day>
        </foundation>
        <rank>NBI/B</rank>
    </team>
    <team idT="t3">
        <name>HTE</name>
        <foundation>
            <year>1919</year>
            <month>06</month>
            <day>01</day>
        </foundation>
        <rank>NBII</rank>
    </team>
    <team idT="t4">
        <name>Veszprém</name>
        <foundation>
            <year>1977</year>
            <month>03</month>
            <day>19</day>
        </foundation>
        <rank>NBI</rank>
    </team>
    <team idT="t5">
        <name>DEAC</name>
        <foundation>
            <year>1919</year>
            <month>10</month>
            <day>05</day>
        </foundation>
        <rank>NBI/B</rank>
    </team>
    <!-- Öt különböző supporter példány egyedi ID-val, adatokkal és idegenkulccsal-->
    <supporter idS="s1" s_t="t1">
        <name>Apollo Tyres</name>
        <amount>100000000</amount>
        <validity>
            <year>2025</year>
            <month>06</month>
            <day>31</day>
        </validity>
    </supporter>
    <supporter idS="s2" s_t="t4">
        <name>Telekom</name>
        <amount>100000000</amount>
        <validity>
            <year>2030</year>
            <month>12</month>
            <day>31</day>
        </validity>
    </supporter>
    <supporter idS="s3" s_t="t3">
        <name>Adidas</name>
        <amount>100000000</amount>
        <validity>
            <year>2024</year>
            <month>01</month>
            <day>01</day>
        </validity>
    </supporter>
    <supporter idS="s4" s_t="t5">
        <name>Hall</name>
        <amount>5000000</amount>
        <validity>
            <year>2029</year>
            <month>12</month>
            <day>01</day>
        </validity>
    </supporter>
    <supporter idS="s5" s_t="t2">
        <name>Erima</name>
        <amount>1000000</amount>
        <validity>
            <year>2030</year>
            <month>10</month>
            <day>15</day>
        </validity>
    </supporter>
    <!-- Öt player példány egyedi ID-val, adatokkal és idegenkulccsal -->
    <player idP="p1" p_t="t1">
        <name>Torma Antal</name>
        <birthdate>
            <year>1994</year>
            <month>09</month>
            <day>02</day>
        </birthdate>
        <post>Kapus</post>
    </player>
    <player idP="p2" p_t="t3">
        <name>Kiss András</name>
        <birthdate>
            <year>1970</year>
            <month>03</month>
            <day>11</day>
        </birthdate>
        <post>Beálló</post>
    </player>
    <player idP="p3" p_t="t2">
        <name>Nagy Róbert</name>
        <birthdate>
            <year>1999</year>
            <month>04</month>
            <day>30 </day>
        </birthdate>
        <post>Irányító</post>
    </player>
    <player idP="p4" p_t="t5">
        <name>Győrfi Ádám</name>
        <birthdate>
            <year>2000</year>
            <month>02</month>
            <day>23</day>
        </birthdate>
        <post>Szélső</post>
    </player>
    <player idP="p5" p_t="t4">
        <name>Dávid Máté</name>
        <birthdate>
            <year>1992</year>
            <month>07</month>
            <day>30</day>
        </birthdate>
        <post>Átlövő</post>
    </player>
    <!-- Öt coach példány egyedi ID-val, adatokkal és idegenkulccsal  -->
    <coach idC="c1" c_t="t5">
        <name>Gipsz Jakab</name>
        <birthdate>
            <year>1980</year>
            <month>05</month>
            <day>26</day>
        </birthdate>
        <licence>C</licence>
    </coach>
    <coach idC="c2" c_t="t1">
        <name>Molnár András</name>
        <birthdate>
            <year>1970</year>
            <month>07</month>
            <day>11</day>
        </birthdate>
        <licence>A</licence>
    </coach>
    <coach idC="c3" c_t="t2">
        <name>Tamás Tamás</name>
        <birthdate>
            <year>1992</year>
            <month>12</month>
            <day>01</day>
        </birthdate>
        <licence>B</licence>
    </coach>
    <coach idC="c4" c_t="t3">
        <name>Bakos Károly</name>
        <birthdate>
            <year>1989</year>
            <month>08</month>
            <day>21</day>
        </birthdate>
        <licence>B</licence>
    </coach>
    <coach idC="c5" c_t="t4">
        <name>Momir Ilic</name>
        <birthdate>
            <year>1986</year>
            <month>01</month>
            <day>30</day>
        </birthdate>
        <licence>B</licence>
    </coach>
    <!-- Öt match példány melyek kettő idegenkulcsot tartalmazznak -->
    <match m_t="t2" m_r="r1">
        <location>Budapest</location>
        <date>2022-10-31</date>
    </match>
    <match m_t="t1" m_r="r3">
        <location>Miskolc</location>
        <date>2022-11-19</date>
    </match>
    <match m_t="t3" m_r="r2">
        <location>Hajdúböszörmény</location>
        <date>2022-12-02</date>
    </match>
    <match m_t="t5" m_r="r4">
        <location>Veszprém</location>
        <date>2023-03-11</date>
    </match>
    <match m_t="t4" m_r="r5">
        <location>Debrecen</location>
        <date>2023-05-20</date>
    </match>
    <!-- Öt referee példány ID-val és adatokkal -->
    <referee idR="r1">
        <name>Katona János</name>
        <birthdate>
            <year>1975</year>
            <month>01</month>
            <day>05</day>
        </birthdate>
        <licence>C</licence>
    </referee>
    <referee idR="r2">
        <name>Tóth István</name>
        <birthdate>
            <year>1972</year>
            <month>09</month>
            <day>22</day>
        </birthdate>
        <licence>A</licence>
    </referee>
    <referee idR="r3">
        <name>Nagy Péter</name>
        <birthdate>
            <year>1993</year>
            <month>11</month>
            <day>11</day>
        </birthdate>
        <licence>A</licence>
    </referee>
    <referee idR="r4">
        <name>Bíró Ádám</name>
        <birthdate>
            <year>1990</year>
            <month>04</month>
            <day>16</day>
        </birthdate>
        <licence>C</licence>
    </referee>
    <referee idR="r5">
        <name>Kiss Olivér</name>
        <birthdate>
            <year>1988</year>
            <month>11</month>
            <day>27</day>
        </birthdate>
        <licence>C</licence>
    </referee>
</handball>
